---
- name: Deploy Simple Calculator Application
  hosts: webserver
  become: yes

  vars:
    app_repo: "https://github.com/22MCAN033/Simple-Calculator.git"
    app_dest: "/var/www/simple-calculator"

  tasks:
    - name: Ensure Nginx is installed
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Ensure Git is installed
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Clone calculator repo
      git:
        repo: "{{ app_repo }}"
        dest: "{{ app_dest }}"
        version: main
        force: yes

    - name: Copy files to Nginx web root
      copy:
        src: "{{ app_dest }}/"
        dest: "/var/www/html/"
        owner: www-data
        group: www-data
        mode: '0644'
      notify: Restart nginx

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
