---
- name: Bootstrap target server and install Nginx
  hosts: all
  become: yes
  gather_facts: yes   # normal fact gathering, system python hi chalega

  vars:
    ansible_python_interpreter: /usr/bin/python3   # system Python for all tasks

  tasks:
    - name: Test Python connectivity
      command: "{{ ansible_python_interpreter }} --version"
      register: python_version
      changed_when: false

    - name: Display Python version
      debug:
        var: python_version.stdout

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Ensure Nginx service is running and enabled
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Create test HTML file
      copy:
        content: "<html><body><h1>Hello from AWX!</h1></body></html>"
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Check if Nginx is accessible
      uri:
        url: http://localhost
        method: GET
        status_code: 200
      register: nginx_status
      ignore_errors: yes

    - name: Display Nginx status
      debug:
        msg: "Nginx is {{ 'running' if nginx_status.status == 200 else 'not accessible' }}"

    - name: Allow Nginx through UFW firewall
      ufw:
        rule: allow
        name: 'Nginx Full'
      ignore_errors: yes
