---
- name: Bootstrap target server and install Nginx
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Ensure Python3, pip and dependencies are installed
      apt:
        name:
          - python3
          - python3-pip
          - python3-setuptools
          - python3-wheel
          - python3-six
        state: present

    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Ensure Nginx service is running and enabled
      service:
        name: nginx
        state: started
        enabled: yes
