---
- name: Bootstrap target server and install Nginx
  hosts: all
  become: yes
  gather_facts: no  # Disable fact gathering initially
  vars:
    ansible_python_interpreter: /usr/bin/python3.8

  tasks:
    - name: Test Python connectivity
      raw: python3.8 --version
      register: python_version
      changed_when: false

    - name: Display Python version
      debug:
        var: python_version.stdout

    - name: Update apt cache
      raw: apt update
      changed_when: false

    - name: Install required Python packages
      raw: |
        apt install -y python3.8 python3.8-dev python3.8-distutils python3-pip python3-setuptools python3-wheel python3-six python3-apt
      register: install_result
      changed_when: install_result.rc == 0

    - name: Ensure Python3.8 is properly linked
      raw: |
        if [ ! -f /usr/bin/python3.8 ]; then
          ln -s /usr/bin/python3.8 /usr/bin/python3.8
        fi
      changed_when: false

    # Now enable fact gathering with proper Python interpreter
    - name: Gather facts with Python 3.8
      setup:
      vars:
        ansible_python_interpreter: /usr/bin/python3.8

    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
      vars:
        ansible_python_interpreter: /usr/bin/python3.8

    - name: Ensure Nginx service is running and enabled
      service:
        name: nginx
        state: started
        enabled: yes
      vars:
        ansible_python_interpreter: /usr/bin/python3.8

    - name: Check if Nginx is accessible
      uri:
        url: http://localhost
        method: GET
        status_code: 200
      register: nginx_status
      ignore_errors: yes
      vars:
        ansible_python_interpreter: /usr/bin/python3.8

    - name: Display Nginx status
      debug:
        msg: "Nginx is {{ 'running' if nginx_status.status == 200 else 'not accessible' }}"

    - name: Allow Nginx through UFW firewall (if UFW is enabled)
      ufw:
        rule: allow
        name: 'Nginx Full'
      ignore_errors: yes
      vars:
        ansible_python_interpreter: /usr/bin/python3.8